version: "3.8"

services:
  teajuda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: math_quest_app
    ports:
      - "8080:10000"
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"